version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  backend:
    depends_on:
      - redis
    build: ./backend
    ports:
      - 3001:3001
    volumes:
      - ./backend/:/usr/src/app
    environment:
      REDIS_HOST: redis

  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/usr/src/app

