version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - 3001:3001
    volumes:
      - ./backend/:/usr/src/app

  frontend:
    container_name: frontend
    depends_on:
      - backend
    build:
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/usr/src/app

