name: Deploy backend

on:
  push:
    branches: [master]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yaml'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Add backend remote origin
        run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_BACKEND_APP_NAME }}.git
      - name: Deploy backend to Heroku
        run: git push heroku `git subtree split --prefix backend master`:master --force
