name: Test frontend

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/ci-frontend.yaml'

jobs:
  test:
    name: Test frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm ci
      - name: Build the site
        run: npm run build
      - name: Run unit tests
        run: npm run test
