name: Test backend

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/test-backend.yaml'

jobs:
  test:
    name: Test backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm ci
      - name: Build the application
        run: npm run build
      - name: Run unit tests
        run: npm test
